# Generated by Django 5.0.7 on 2025-01-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='month10_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='month11_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='month12_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='month1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='month2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='month3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='month4_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='month5_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='month6_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='month7_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='month8_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='month9_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='start_date',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
