# Generated by Django 5.0.7 on 2026-06-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productionplan_end_date_productionplan_month10_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
